#!/bin/sh
#
# batch-subject-editor - helper script to change subject lines with mutt
#
# Based on an idea by David Champion <dgc at uchicago.edu>
#
# Copyright © 2008 martin f. krafft <madduck@madduck.net>
# Released under the terms of the Artistic Licence 2.0
#
set -eu

printf 'Enter new subject: ' >/dev/tty
read subj </dev/tty

if [ -z "${subj:-}" ]; then
  echo No subject specified. >&2
  exit 1
fi

RE_REPLY='((re|aw|antwort)([[(]?[[:digit:]]+[)]]?)?):[[:space:]]*'
RE_SUBJ_PREFIX="^Subject:[[:space:]]*(${RE_REPLY})*"
RE_SUBJ='.*'
EDITOR="sed -i -re \"s,(${RE_SUBJ_PREFIX})${RE_SUBJ},\\\1$subj,i\""

printf "set editor='${EDITOR} %s'"
