[mypy]

[mypy-pulumi_aws]
# TODO: this seems to work!! unaldulterated pulumi_aws dunder init, runs fast,
# still detects type problems? so maybe what this means is /don't recurse
# deeper into pulumi_aws/ which is perfect!
follow_imports = skip
