session_name: main
windows:
  # TODO: change this to eg 'code' and embrace per-project sessions?
- window_name: "${MUX_SESSION}"
  focus: true
  layout: main-vertical
  options:
    # 3x80col vim + 2 pane splits (+ 3 signcolumns for CoC)
    main-pane-width: 245
  shell_command_before: "wk ${MUX_SESSION}"
  panes:
    - vim .
    - focus: true
    - lazygit
